#!/usr/bin/env bash
clang -o "$3" -O1 --target=riscv64-linux-gnu -march=rv64gcvzbb_zba_zbc_zbs_zvfh "$1" > "$2" && \
qemu-riscv64 -cpu rv64,v=on,vext_spec=v1.0,rvv_ta_all_1s=on,rvv_ma_all_1s=on,vlen=256 -L /usr/riscv64-linux-gnu/ "$3"
